### ISSUE TITLE
Missing info in data dictionary BBM2022

### ISSUE THREAD

**Issue by DPLATA** [fantasydatapros/best-ball-data-bowl#5]
In the dataset of BBM we have the following ids:
['draft_id', 'draft_entry_id', 'tournament_entry_id', 'tournament_round_draft_entry_id']
But in the dictionary there are only two ids descriptions
['draft_id', 'tournament_entry_id']

So we are missing: 'draft_entry_id' and 'tournament_round_draft_entry_id' descriptions

**Comment by bendominguez0111** [comment]
Yes, it looks like these two columns were added for the postseason CSVs but not for the regular season CSVs. I will add descriptions for those columns in the README.
